package jeffparsons:mvp-game;

world startup-mod {
    export startup-mod-api;
    import mvp-api;
}

interface startup-mod-api {
    use mvp-api.{commands};

    run: func(commands: borrow<commands>) -> string;
}

interface mvp-api {
    resource commands {
        spawn-stuff: func();
    }
}